package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// LionTex Brand Colors (Warm Amber Lion Gold & Smart Tech Slate/Cyan)
val LionGoldPrimary = Color(0xFFD97706)
val LionGoldPrimaryDark = Color(0xFFFBBF24)
val LionSlateDark = Color(0xFF0F172A)
val LionSlateCard = Color(0xFF1E293B)
val LionCyanAccent = Color(0xFF0284C7)
val LionCyanAccentDark = Color(0xFF38BDF8)
val LionEmeraldSuccess = Color(0xFF10B981)

val LightPrimary = Color(0xFFB45309)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFEF3C7)
val LightOnPrimaryContainer = Color(0xFF78350F)
val LightSecondary = Color(0xFF0284C7)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE0F2FE)
val LightOnSecondaryContainer = Color(0xFF0369A1)
val LightTertiary = Color(0xFF0F766E)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFCCFBF1)
val LightOnTertiaryContainer = Color(0xFF115E59)
val LightBackground = Color(0xFFF8FAFC)
val LightOnBackground = Color(0xFF0F172A)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF0F172A)
val LightSurfaceVariant = Color(0xFFF1F5F9)
val LightOnSurfaceVariant = Color(0xFF475569)
val LightOutline = Color(0xFFCBD5E1)

val DarkPrimary = Color(0xFFFBBF24)
val DarkOnPrimary = Color(0xFF451A03)
val DarkPrimaryContainer = Color(0xFF78350F)
val DarkOnPrimaryContainer = Color(0xFFFEF3C7)
val DarkSecondary = Color(0xFF38BDF8)
val DarkOnSecondary = Color(0xFF082F49)
val DarkSecondaryContainer = Color(0xFF0369A1)
val DarkOnSecondaryContainer = Color(0xFFE0F2FE)
val DarkTertiary = Color(0xFF2DD4BF)
val DarkOnTertiary = Color(0xFF042F2E)
val DarkTertiaryContainer = Color(0xFF115E59)
val DarkOnTertiaryContainer = Color(0xFFCCFBF1)
val DarkBackground = Color(0xFF0B0F17)
val DarkOnBackground = Color(0xFFF8FAFC)
val DarkSurface = Color(0xFF111827)
val DarkOnSurface = Color(0xFFF8FAFC)
val DarkSurfaceVariant = Color(0xFF1F2937)
val DarkOnSurfaceVariant = Color(0xFF94A3B8)
val DarkOutline = Color(0xFF334155)
